# Generated by Django 5.0.6 on 2026-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_profile_theme_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', '☁️ daylight'), ('dark', '🌑 midnight'), ('pastel', '🌸 blossom')], default='light', max_length=20),
        ),
    ]
